patient_name=input("patient_name: ")
phone_number=input("phone_number: ")
next_of_kin=input("next_of_kin: ")
period=input("4 months")
print(f"the doctor admitted patient of patient name {patient_name} of phone number {phone_number} and next of kin {next_of_kin} for a period of{period}")